CAR_RELATED_WORDS = [
    "car",
    "automobile",
    "vehicle",
    "engine",
    "wheels",
    "tires",
    "steering wheel",
    "gearbox",
    "brakes",
    "spoiler",
    "mirrors",
    "air conditioning",
    "seats",
    "trunk",
    "hood",
    "bumper",
    "lights",
    "headlights",
    "indicators",
    "exhaust",
    "fuel tank",
    "fuel",
    "diesel",
    "gasoline",
    "electric",
    "hybrid",
    "charger",
    "battery",
    "air filter",
    "turbo",
    "intercooler",
    "suspension",
    "shock absorbers",
    "rims",
    "drivetrain",
    "child seat",
    "seat belt",
    "navigation",
    "radio",
    "audio system",
    "alarm",
    "horn",
    "wipers",
    "washers",
    "license plate",
    "roof",
    "window",
    "door",
    "central lock",
    "keys",
    "seat",
    "upholstery",
    "abs",
    "esp",
    "asr",
    "rearview camera",
    "parking sensors",
    "cruise control",
    "speedometer",
    "tachometer",
    "onboard computer",
    "tachograph",
    "catalytic converter",
    "inspection",
    "insurance",
    "highway",
    "road",
    "roundabout",
    "intersection",
    "traffic light",
    "ticket",
    "driver's license",
    "instructor",
    "workshop",
    "mechanic",
    "tow truck",
    "gas station",
    "car wash",
    "service",
    "leasing",
    "loan",
    "dealership",
    "purchase",
    "sale",
    "advertisement",
    "car lot",
    "test drive",
    "drifting",
    "rally",
    "racing",
    "race track",
    "tuning",
    "toyota",
    "ford",
    "chevrolet",
    "honda",
    "nissan",
    "bmw",
    "mercedes-benz",
    "volkswagen",
    "audi",
    "porsche",
    "lexus",
    "hyundai",
    "kia",
    "mazda",
    "subaru",
    "jeep",
    "dodge",
    "ram",
    "buick",
    "cadillac",
    "chrysler",
    "gmc",
    "tesla",
    "volvo",
    "jaguar",
    "land rover",
    "mini",
    "fiat",
    "alfa romeo",
    "ferrari",
    "lamborghini",
    "maserati",
    "bentley",
    "rolls-royce",
    "aston martin",
    "mclaren",
    "pagani",
    "bugatti",
    "peugeot",
    "renault",
    "citroën",
    "skoda",
    "seat",
    "opel",
    "saab",
    "mitsubishi",
    "suzuki",
    "isuzu",
    "acura",
    "infiniti",
    "lincoln",
    "genesis",
    "hummer",
    "saturn",
    "pontiac",
    "oldsmobile",
    "scion",
    "smart",
    "daihatsu",
    "tata",
    "mahindra",
    "rivian",
    "lucid",
    "polestar",
    "fisker",
    "koenigsegg",
    "spyker",
    "ariel",
    "caterham",
    "lotus",
    "morgan",
    "rover",
    "mg",
    "lancia",
    "dacia",
    "holden",
    "proton",
    "perodua",
    "ssangyong",
    "geely",
    "byd",
    "great wall",
    "changan",
    "chery",
    "nio",
    "xpeng",
    "wuling",
    "car",
    "automobile",
    "vehicle",
    "truck",
    "pickup",
    "suv",
    "van",
    "bus",
    "motorcycle",
    "bike",
    "bicycle",
    "scooter",
    "moped",
    "atv",
    "rv",
    "camper",
    "trailer",
    "semi-truck",
    "tractor",
    "ambulance",
    "fire truck",
    "police car",
    "taxi",
    "rideshare",
    "limousine",
    "minivan",
    "convertible",
    "coupe",
    "sedan",
    "hatchback",
    "wagon",
    "roadster",
    "sports car",
    "electric vehicle",
    "hybrid vehicle",
    "self-driving car",
    "autonomous vehicle",
    "skateboard",
    "rollerblades",
    "hoverboard",
    "segway",
    "go-kart",
    "snowmobile",
    "golf cart",
    "mail truck",
    "garbage truck",
    "delivery van",
    "moving truck",
    "food truck",
    "construction vehicle",
    "cement mixer",
    "bulldozer",
    "excavator",
    "forklift",
    "dump truck",
    "tanker truck",
    "tow truck",
    "school bus",
    "shuttle bus",
    "tour bus",
    "double-decker bus",
    "coach",
    "charter bus",
    "bus rapid transit",
    "trolley",
    "streetcar",
    "light rail",
    "tram",
    "train",
    "subway",
    "metro",
    "monorail",
    "funicular",
    "cable car",
    "carriage",
    "buggy",
    "rickshaw",
    "tuk-tuk",
    "sled",
    "dog sled",
    "horse-drawn carriage",
    "chariot"
]